import type { TemplateDefinition } from "@/types";

export const templates: TemplateDefinition[] = [
  {
    id: "tpl_crm",
    slug: "crm-workspace",
    name: "CRM Workspace",
    category: "Sales Ops",
    collection: "Customer Systems",
    complexity: "Moderate",
    description: "Pipeline, accounts, contact timelines, revenue health, and task ownership in one editable runtime.",
    preview: "Account table, deal stages, revenue cards, and activity feed.",
    tags: ["crm", "sales", "accounts", "pipeline"],
    metrics: [
      { label: "Objects", value: "6" },
      { label: "Views", value: "4" },
      { label: "Automations", value: "3" },
    ],
    schemaId: "crm-runtime",
  },
  {
    id: "tpl_hr",
    slug: "hr-dashboard",
    name: "HR Dashboard",
    category: "People Ops",
    collection: "Operations",
    complexity: "Simple",
    description: "Headcount, onboarding queues, candidate status, and employee signals for lean people teams.",
    preview: "Hiring funnel, onboarding checklist, and employee directory.",
    tags: ["hr", "people", "hiring", "onboarding"],
    metrics: [
      { label: "Objects", value: "5" },
      { label: "Views", value: "3" },
      { label: "Automations", value: "2" },
    ],
    schemaId: "hr-runtime",
  },
  {
    id: "tpl_admin",
    slug: "admin-panel",
    name: "Admin Panel",
    category: "Internal Ops",
    collection: "Control Rooms",
    complexity: "Advanced",
    description: "Permissions, system entities, audit events, and operational controls for internal teams.",
    preview: "Role matrix, user table, audit stream, and system health modules.",
    tags: ["admin", "permissions", "audit", "ops"],
    metrics: [
      { label: "Objects", value: "8" },
      { label: "Views", value: "6" },
      { label: "Automations", value: "4" },
    ],
    schemaId: "admin-runtime",
  },
  {
    id: "tpl_analytics",
    slug: "analytics-dashboard",
    name: "Analytics Dashboard",
    category: "Revenue Ops",
    collection: "Insights",
    complexity: "Advanced",
    description: "Live metrics, segment filters, variance alerts, and executive reporting surfaces.",
    preview: "Metric cards, line chart, cohort table, and alert workflow.",
    tags: ["analytics", "revenue", "dashboard", "kpi"],
    metrics: [
      { label: "Objects", value: "7" },
      { label: "Views", value: "5" },
      { label: "Automations", value: "5" },
    ],
    schemaId: "analytics-runtime",
  },
  {
    id: "tpl_inventory",
    slug: "inventory-system",
    name: "Inventory System",
    category: "Supply Ops",
    collection: "Operations",
    complexity: "Moderate",
    description: "Stock movement, reorder triggers, vendor visibility, and warehouse exceptions.",
    preview: "Inventory table, reorder queue, vendor cards, and status timeline.",
    tags: ["inventory", "supply", "warehouse", "vendors"],
    metrics: [
      { label: "Objects", value: "6" },
      { label: "Views", value: "4" },
      { label: "Automations", value: "4" },
    ],
    schemaId: "inventory-runtime",
  },
  {
    id: "tpl_support",
    slug: "support-workspace",
    name: "Support Workspace",
    category: "Customer Ops",
    collection: "Customer Systems",
    complexity: "Simple",
    description: "Ticket triage, SLA risk, customer context, macros, and escalation workflows.",
    preview: "Ticket queue, SLA indicators, customer panel, and response workflow.",
    tags: ["support", "tickets", "sla", "customers"],
    metrics: [
      { label: "Objects", value: "5" },
      { label: "Views", value: "4" },
      { label: "Automations", value: "3" },
    ],
    schemaId: "support-runtime",
  },
];

export const categories = Array.from(new Set(templates.map((template) => template.category)));
export const complexities = ["Simple", "Moderate", "Advanced"] as const;
export const collections = Array.from(new Set(templates.map((template) => template.collection)));
